# Generated by Django 2.0.3 on 2018-04-04 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('jcont', django_mysql.models.JSONField(default=posts.models.json_posts_default)),
                ('institute', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institutes')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-posted_at'],
            },
        ),
    ]
