# Generated by Django 2.0.3 on 2018-04-04 14:51

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('user_id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='auth.User')),
                ('no_liked', models.IntegerField(default=0)),
                ('no_likes', models.IntegerField(default=0)),
                ('no_comments', models.IntegerField(default=0)),
                ('lastonline', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_counter',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='auth.User')),
                ('j_user', django_mysql.models.JSONField(default=dict)),
                ('institute', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institutes')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
